server {
    listen 80;
    server_name localhost;

    # Servir archivos estáticos desde la raíz
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Redirigir las peticiones a /api/ al backend
    location /api/ {
        proxy_pass http://backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
