services:
  db:
    image: postgres:16-alpine   # Versión fija, evita error de pg18+
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata_new:/var/lib/postgresql/data   # Nombre de volumen nuevo
    networks:
      - app-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: vln14777/backend:latest
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-net
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/api/status"]
      interval: 15s
      timeout: 5s
      retries: 3

  frontend:
    image: vln14777/frontend:latest
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  app-net:
    driver: bridge

volumes:
  pgdata_new:   # Declaración del nuevo volumen
